create table employee (id bigint generated by default as identity, email varchar(255), name varchar(255), phone_number varchar(255), position varchar(255), primary key (id));
create table employee (id bigint generated by default as identity, email varchar(255), name varchar(255), phone_number varchar(255), position varchar(255), primary key (id));
create table employee (id bigint generated by default as identity, email varchar(255), name varchar(255), phone_number varchar(255), position varchar(255), primary key (id));
