DROP TABLE IF EXISTS Employee;
CREATE TABLE Employee (
	id BIGINT AUTO_INCREMENT  PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	position VARCHAR(50) NOT NULL,
	phone VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    avatar VARCHAR(1000) NOT NULL,
    skills VARCHAR(1000) NOT NULL,
    levels VARCHAR(1000) NOT NULL
);
